bindAddr = "0.0.0.0"
bindPort = 7000
#kcpBindPort = 7000
quicBindPort = 7000

vhostHTTPPort = 80
vhostHTTPSPort = 443

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
transport.tls.force = false

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"
webServer.pprofEnable = false

log.to = "/usr/local/frp/frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false

auth.method = "token"
auth.token = "12345678"

allowPorts = [

]

allowPorts = [
  { start = 10001, end = 50000 },
  { single = 60000 }
]

maxPortsPerClient = 12  # 最大可连接端口数量,指：31400-31409,53389共11个端口号可用，如需要增加需要更改数字即可！
udpPacketSize = 1500
natholeAnalysisDataReserveHours = 168


# 重启服务：systemctl restart frps
# 查询状态：systemctl status frps
